
// This file is autogenerated from ../../neopixel.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// Only uses MOSI on H4P11
#define NPX_SPI MT3620_RDB_HEADER4_ISU1_SPI

// SPI CS A (not used)
#define NPX_SPI_CS MT3620_SPI_CS_A

